Estudiante		Linea	Lotka	Total
====================================================================
DavidAleman 		35[6]	60	95
DavidDavila 		35[6]	60	95
MariaCamilaRemolina	40[3]	35[4]	75
JesusPrada		40[3]	35[4]	75
JuanDavidGodoy		35[1]	35[2]	70
HMMartinezGomez 	35[1]	35[2]	70
JuanRafaelAlvarez	35[5]	35[5]	70
SebastianCalderon	35[5]	35[5]	70
MurielPerez		25[9]	35[8]	60
SergioCotrino		25[9]	35[8]	60
JulianaAyala 		20[10]	30[11]	50
NicolasRomero		20[10]	30[11]	50


[1] La forma de recorrer el parametro A no funciona si se intenta con
otra linea. Funciona asi porque de alguna manera hicieron un fit a ojo
y empiezan cerca de la respuesta. 
[2] Las graficas no tienen ejes y no se explica que es la escala de
color. Tambien suena como un fit a ojo porque los pasos de 0.05 son muy pequenos para que haya una
convergencia con apenas 1000 pasos de la cadena. Se debia construir
una sola likelihood, no dos. Si el programa esta devolviendo el chi^2,
entonces la condicion sobre rx esta mal hecha. 
[3] (luffy? robin? sanji? luffylihood?) 
El pito no funciona si no se tiene instalado
del comando play. El makefile esta mal hecho: siempre ejecuta el
programa sin importar si ya se hicieron las graficas. 
[4] Si la funcion likelihood en realidad esta devolviendo el chi^2,
entonces la condicion para decidir si salta o no esta mal. 
[5] Las graficas que se pedian eran de un histograma bidimensional.
[6] Las graficas que se pedian eran de un histograma bidimensional.
Habia que hacer un fit a una parabola. 
[8] Entregado un dia tarde. Si la funcion de likelihood devuelve
chi^2, entonces el test con oracle = l_prime/l_init esta mal. 
Por otro lado el
programa da un error: 
create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=2,6,0).
Traceback (most recent call last):
  File "fitLV.py", line 75, in <module>
    y_init = my_model(alpha_walk[0], beta_walk[0], gamma_walk[0], delta_walk[0])
  File "fitLV.py", line 51, in my_model
    r.integrate(r.t+dt)
  File "/usr/lib/python2.7/dist-packages/scipy/integrate/ode.py", line 326, in integrate
    self.f_params,self.jac_params)
  File "/usr/lib/python2.7/dist-packages/scipy/integrate/ode.py", line 749, in run
    x,y,iwork,idid = self.runner(*((f,t0,y0,t1) + tuple(self.call_args)))
_dop.error: failed in processing argument list for call-back fcn.
[9] Entregado un dia tarde. Si la funcion de likelihood devuelve
chi^2, entonces el test con oracle = l_prime/l_init esta mal. Tampoco
se estimaron las incertidumbres sobre los parametros.  
[10] El makefile debe ejecutar un script en python y producir todas
las graficas automaticamente, no abrir un notebook. Si estan
devolviendo el chi^2, entonces el test sobre psi para hacer la cadena
esta mal implementado. 
[11] No hay makefile. El archivo en python da errores al
ejecutarse. El test sobre alpha_check es incorrecto. No hay estimacion
sobre las incertidumbres de los parametros.
